project_id = "svxvjoirolzsghhomwfo"

[functions.firecrawl-scrape]
verify_jwt = false

[functions.firecrawl-map]
verify_jwt = false

[functions.scrape-marketplace]
verify_jwt = false

[functions.process-listings]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
